music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources
end

music_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

music_app/app/models/band.rb
class Band < ApplicationRecord
end

music_app/app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  validates :password, length: { minimum: 8, allow_nil: true }
  validates :password_digest, presence: true
  validates :session_token, presence: true, uniqueness: true

  attr_reader :password

  after_initialize :ensure_session_token

  def self.generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end
end

music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def log_in_user!(user)
    session[:session_token] = user.reset_session_token!
  end

  def current_user
    return nil if session[:session_token].nil?
    @current_user ||= User.find_by(session_token: session[:session_token])
  end
end

music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    user = User.find_by_credentials(
      params[:user][:email],
      params[:user][:password]
    )
    if user.nil?
      flash.now[:errors] = ["Incorrect username/password."]
      render :new
    else
      log_in_user!(user)
      redirect_to user_url(user)
    end
  end

  def destroy
    if current_user
      current_user.reset_session_token!
      session[:session_token] = nil
      redirect_to new_session_url
    else
      flash.now[:errors] = ["Can't find user."]
      redirect_to user_url(current_user)
    end
  end
end

music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in_user!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    render :show
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

music_app/app/helpers/application_helper.rb
module ApplicationHelper
end

music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <h1><font size="10" color="green"><i>Music App</i></font></h1>
    <% if current_user %>
      <!-- <%= button_to "Sign out", session_url, method: 'delete'%> -->
      <form action="<%= session_url %>" method="post">
        <input type="hidden" name="_method" value="delete"/>
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"/>
        <input type="submit" value="Sign out"/>
      </form>
    <% else %>
      <% unless controller_name == "sessions" %>
        <!-- <%= link_to "Sign in", new_session_url%> -->
        <a href="<%= new_session_url %>">Sign in</a>
      <% end %>
      <% unless controller_name == "users" %>
        <!-- <%= link_to "Sign up", new_user_url%> -->
        <a href="<%= new_user_url %>">Sign up</a>
      <% end %>
    <% end %>
    <%= yield %>
    <% if flash[:errors] %>
      <%= flash[:errors].join(", ") %>
    <% end %>
  </body>
</html>

music_app/app/views/users/new.html.erb
<h1>Please Create an Account</h1>
<form action='<%= users_url %>', method='post'>
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <label for="user_email">Email</label>
  <input type="text"
    name="user[email]"
    id="user_email"
    value="<%= @user.email %>">
  <br>

  <label for="user_password">Password</label>
  <input type="password"
    name="user[password]"
    id="user_password"
    value="<%= @user.password %>">
  <br>

  <input type="submit">
</form>

music_app/app/views/users/show.html.erb
<section class="page">
  <div class="centered-box">
    <h2>User Profile</h2>
      <p> Email: <%= current_user.email %> </p>
  </div>
</section>